# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_candidate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.IntegerField(default=1),
        ),
    ]
