# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20160113_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'verbose_name_plural': 'criteria'},
        ),
        migrations.RemoveField(
            model_name='criterion',
            name='sequence',
        ),
        migrations.AlterOrderWithRespectTo(
            name='criterion',
            order_with_respect_to='category',
        ),
    ]
