# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 08:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20160113_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Can not be lesser than 1%'), django.core.validators.MaxValueValidator(100, 'Can not be more than 100%')], verbose_name=()),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Can not be lesser than 1%'), django.core.validators.MaxValueValidator(100, 'Can not be more than 100%')], verbose_name=()),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Can not be lesser than 0'), django.core.validators.MaxValueValidator(100, 'Can not be more than 100')], verbose_name=()),
        ),
    ]
